membre.md

Présentation Blue

---

membre.md

Salut à tous !

---

membre.md

J'ai corrigé deux/trois fautes, essayé de mettre en place un formattage cohérent au niveau des séparations et des noms de famille des gens (sauf pour le petit dernier, je ne sais pas lequel est le prénom haha)

Update formatting and typos

---

membre.md

Matteokocken

---

README.md

Mise à jour du code de conduite : 
- Rendre l'accès aux visiteurs moins restrictif.
- Instaurer un status de membre officiel clair. 
- Amélioration du code de conduite (plus concis et plus clair).

Mise à jour code de conduite

---

README.md

J'ai corrigé encore quelques fautes puis revu la mise en page pour la liste des channels notamment.

Fix some typos and formatting

---

membre.md

J'ai oublié de mettre la présentation sur le dépôt Github. J'ai donc copié celle que j'avais posté sur le Discord.

Présentation de LightDiscord

---

CONTRIBUTING.md

Mise à jour du code de conduite pour quelque chose de plus explicite pour les membres de la communauté (non habitué).
- Laisser une marge de manœuvre dans la création des salons pour les Mentors et Fondateurs (qui nous restreint aujourd'hui).
La pull-request est ouverte à l'amélioration et à l'ajout de règles potentiellement manquante.

Mise à jour du code de contribution

---

README.md

Durcissement des règles sur le pseudonyme des membres de la communauté (ainsi que sur la flexibilité du changement).

Ajout d'une règle sur les pseudonymes des membres

---

README.md

Ajout d'une règle de rigueur sur la présentation.

Ajout d'une règle de rigueur sur la présentation

---

README.md

Revert " Proposition: Ajout d'un chan pour les projets"

---

README.md

Reverts ES-Community/Code-of-conduct#53

Revert "Revert " Proposition: Ajout d'un chan pour les projets""

---

aide.md

- split roles by specification (Front/Back/BDD/ Techno/Langage)
- alpha ordering (Clean search)
- add website link to have direct access if interested

split roles by specification and alpha ordering

---

README.md

Suite à l'issue  #57 ajout du channel sur le code de conduite

Add channel #jobs 

---

README.md

Une petite mise à jour du code de conduite dans l'objectif de rafraîchir et/ou corriger des petites incohérences.
Ajout d'une liste de règles pour les salons (plusieurs règles viendront s'ajouter à cette liste à long terme).

Mise à jour du code de conduite

---

sanctions.md

Nouveau draft du code de conduite sur les sanctions applicables ! 
Ce draft à pour objectif de:
- Fournir un guide pour les mentors.
- Mettre au clair les sanctions encourut en cas d'infraction du code de conduite.
- Protéger les membres contre les injustices.

Sanctions (draft)

---

README.md

- ECMAScript
- JavaScript
- Node.js

quelques corrections orthographiques

---

README.md

Pour se partager des articles, outils, librairies abordables pour des devs, les bonnes pratiques, choses à éviter, etc..

Ajout d'une section web app security

---

README.md

Je pense qu'on aborde suffisamment souvent le sujet pour qu'il mérite son salon dédié.

Ajout du salon #typescript

---

README.md

Attente du délai d'une semaine pour la PR #83 .
A merge le 13.02.20

Revert "Ajout du salon #typescript"

---

README.md

Ajout de détails complémentaires pour les sanctions et contributions pour permettre aux membres d'être mieux informé. Nous avons bien deux fichiers séparés qui vont traiter des sanctions et des règles pour les contributions mais nous ne faisons aucun lien au sein du README.md lui-même :\
C'est un draft (en attente de vos reviews pour pallier ma terrible maîtrise du français 😅).

Mise à jour du code de conduite pour les sanctions et contributions

---

README.md

Ce lien redirige vers le channel présentation

modification du lien d'invitation

---

README.md

Bonjour, je me permet de faire une PR afin de changer le nom des canaux (#autres) sur le discord.
Pour rappel le problème est que quand on veux upload un fichier (photo par exemple) depuis le téléphone, il n'y a aucun moyen de savoir ou il va partir ... 
Qu'en pensez vous ?
close: #99

doc: reword channel name

---

README.md

fix: update links and jobs format

---

README.md

C'est un sujet dont on a pas mal discuté ces derniers temps sur le Discord.
Une des informations primordiales sur les annonces d'emploi est une fourchette du salaire.
C'est donc dans cette idée que je propose l'ajout de ce paragraphe dans le CoC

feat(jobs)!: salary hint is now mandatory
